apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-replicaset
  namespace: cats-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cats
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - name: cats
        image: 309676119673.dkr.ecr.us-east-1.amazonaws.com/cats:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ecr-registry-secret
